name: olden_era_wiki
description: "Unofficial wiki companion for Heroes of Might and Magic: Olden Era."
publish_to: "none"
version: 1.0.4+202606142340

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqlite3: ^2.4.6
  sqlite3_flutter_libs: ^0.5.24
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  path: ^1.9.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  image: ^4.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/db/wiki.sqlite
    - assets/icons.json
    - assets/images/raw/sprite/
    - assets/images/raw/texture/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true
